### ISSUE TITLE
react-paperjs-editor is private?

### ISSUE THREAD

**Issue by max3a3** [psychobolt/ProtoStage#9]
I am trying to build and can't access @psychobolt/react-paperjs-editor

**Comment by psychobolt** [comment]
It shouldn't be: https://www.npmjs.com/package/@psychobolt/react-paperjs-editor

**Comment by max3a3** [comment]
Yes the package is public, I went to https://github.com/psychobolt/react-paperjs-editor to check the source code and saw it is private. Will it remain closed source or it will be opened in the future. I remember checking it last year when it was open

**Comment by psychobolt** [comment]
Ah yes, it is open source: https://github.com/psychobolt/react-paperjs/tree/master/packages/react-paperjs-editor. It was refactored into a monorepo project. The links to the project should be updated, but not yet pushed to npm. This requires a wait for a new version.

**Comment by psychobolt** [comment]
https://github.com/psychobolt/react-paperjs/issues/5

**Comment by max3a3** [comment]
Thanks, I am still learning about how to use paper js in react, and your projects has been helpful
